'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rsMain
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.rsMain", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT u.UserName AS [iUser] ,U.[Password],IsNull(th.Fname,&apos;&apos;) + &apos; &apos; + IsNull(th.Lname,&apos;&apos;) AS UserName,
        '''IsNull(tp.PrefixNameFull,&apos;&apos;) + IsNull(th.Fname,&apos;&apos;) + &apos; &apos; + IsNull(th.Lname,&apos;&apos;) AS UserNameFull,
        '''u.TeacherNo
        '''FROM  Personal.dbo.tblUserName AS U
        '''LEFT JOIN Personal.dbo.tblTeacherHis AS TH ON u.TeacherNo = th.TeacherNo
        '''LEFT JOIN BaseData.dbo.tblPrefix AS tp ON th.PrefixNo = tp.PrefixNo
        '''WHERE [username] = &apos;{0}&apos; AND U.[Password] = &apos;{1}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property checkUser() As String
            Get
                Return ResourceManager.GetString("checkUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Source=.\sqlexpress;Initial Catalog=Tabain;Persist Security Info=True;User ID=sa;Password=mengae.
        '''</summary>
        Friend Shared ReadOnly Property strConn() As String
            Get
                Return ResourceManager.GetString("strConn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT tsr.No_Room,tsr.StdNo,  ts.Fname , ts.Lname 
        '''FROM Tabain.dbo.tblStudentRoom AS tsr
        '''LEFT JOIN Tabain.dbo.tblStudentNumber SN ON tsr.StdNo = sn.StdNo
        '''LEFT JOIN Tabain.dbo.tblStudent AS ts ON sn.StdNoRef = ts.StdNoRef
        '''LEFT JOIN BaseData.dbo.tblPrefix AS tp ON ts.PreFixNo = tp.PrefixNo
        '''WHERE tsr.LavelNo + tsr.DepartNo + tsr.RoundNo + tsr.[Year] + tsr.Room = &apos;{0}&apos;
        '''  Order BY No_Room,tsr.StdNo.
        '''</summary>
        Friend Shared ReadOnly Property Student() As String
            Get
                Return ResourceManager.GetString("Student", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE 
        '''FROM Tabain.dbo.tblStudent
        '''WHERE stdnoref IN (SELECT StdNoRef FROM Tabain.dbo.tblStudentNumber AS tsn WHERE stdno = @p1 ).
        '''</summary>
        Friend Shared ReadOnly Property StudentDel() As String
            Get
                Return ResourceManager.GetString("StudentDel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT tsr.No_Room,tsr.StdNo,  tp.PrefixNameFull + ts.Fname + &apos; &apos; + ts.Lname AS StdName
        ''',tp.PrefixNameFullEng + ts.FNameEng + &apos; &apos; + ts.LNameEng AS StdNameEng
        '''FROM Tabain.dbo.tblStudentRoom AS tsr
        '''LEFT JOIN Tabain.dbo.tblStudentNumber SN ON tsr.StdNo = sn.StdNo
        '''LEFT JOIN Tabain.dbo.tblStudent AS ts ON sn.StdNoRef = ts.StdNoRef
        '''LEFT JOIN BaseData.dbo.tblPrefix AS tp ON ts.PreFixNo = tp.PrefixNo
        '''WHERE tsr.LavelNo + tsr.DepartNo + tsr.RoundNo + tsr.[Year] + tsr.Room = &apos;{0}&apos;
        '''  Order BY No_Room,tsr.StdNo.
        '''</summary>
        Friend Shared ReadOnly Property StudentRoom() As String
            Get
                Return ResourceManager.GetString("StudentRoom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Tabain.Dbo.tblStudent 
        '''SET Fname = @p1, Lname = @p2 
        '''From _Tabain.Dbo.tblStudent TS
        '''LEFT JOIN _Tabain.Dbo.tblStudentNumber TN ON TS.StdNoRef = TN.StdNoRef Where TN.StdNo = @p3.
        '''</summary>
        Friend Shared ReadOnly Property StudentUpdate() As String
            Get
                Return ResourceManager.GetString("StudentUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT DepartName,tl.DepartNamefull 
        '''FROM BaseData.dbo.tblDepart AS tl
        '''WHERE tl.DepartNo = &apos;{0}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property tblDepart() As String
            Get
                Return ResourceManager.GetString("tblDepart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT LavelName,LavelNameFull
        '''FROM BaseData.dbo.tblLavel AS tl
        '''WHERE tl.LavelNo = &apos;{0}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property tblLavel() As String
            Get
                Return ResourceManager.GetString("tblLavel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT RoundName
        '''FROM BaseData.dbo.tblRound AS tl
        '''WHERE tl.RoundNo = &apos;{0}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property tblRound() As String
            Get
                Return ResourceManager.GetString("tblRound", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
